// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/v1/collection.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Collections represents a collection of documents
type Collection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// unique id of the collection
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// update timestamp
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// name of the collection (must be unique)
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// dimension of the vector space
	VectorDimension int32 `protobuf:"varint,5,opt,name=vector_dimension,json=vectorDimension,proto3" json:"vector_dimension,omitempty"`
	// schema for metadata
	MetadataSchema map[string]*structpb.Struct `protobuf:"bytes,6,rep,name=metadata_schema,json=metadataSchema,proto3" json:"metadata_schema,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// number of documents in this collection
	DocumentCount int64 `protobuf:"varint,7,opt,name=document_count,json=documentCount,proto3" json:"document_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collection) Reset() {
	*x = Collection{}
	mi := &file_api_proto_v1_collection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_collection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_collection_proto_rawDescGZIP(), []int{0}
}

func (x *Collection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Collection) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Collection) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Collection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Collection) GetVectorDimension() int32 {
	if x != nil {
		return x.VectorDimension
	}
	return 0
}

func (x *Collection) GetMetadataSchema() map[string]*structpb.Struct {
	if x != nil {
		return x.MetadataSchema
	}
	return nil
}

func (x *Collection) GetDocumentCount() int64 {
	if x != nil {
		return x.DocumentCount
	}
	return 0
}

// CreateCollectionRequest represents a request to create a collection
type CreateCollectionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of the collection (must be unique)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// dimension of the vector space
	VectorDimension int32 `protobuf:"varint,2,opt,name=vector_dimension,json=vectorDimension,proto3" json:"vector_dimension,omitempty"`
	// schema for metadata
	MetadataSchema map[string]*structpb.Struct `protobuf:"bytes,3,rep,name=metadata_schema,json=metadataSchema,proto3" json:"metadata_schema,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_api_proto_v1_collection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_collection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_collection_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCollectionRequest) GetVectorDimension() int32 {
	if x != nil {
		return x.VectorDimension
	}
	return 0
}

func (x *CreateCollectionRequest) GetMetadataSchema() map[string]*structpb.Struct {
	if x != nil {
		return x.MetadataSchema
	}
	return nil
}

// CreateCollectionResponse represents a response to create a collection
type CreateCollectionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// created collection
	Collection    *Collection `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionResponse) Reset() {
	*x = CreateCollectionResponse{}
	mi := &file_api_proto_v1_collection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionResponse) ProtoMessage() {}

func (x *CreateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_collection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionResponse.ProtoReflect.Descriptor instead.
func (*CreateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_collection_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCollectionResponse) GetCollection() *Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

// ListCollectionRequest represents a request to retrieve a collection
type ListCollectionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the collection to retrieve
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionRequest) Reset() {
	*x = ListCollectionRequest{}
	mi := &file_api_proto_v1_collection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionRequest) ProtoMessage() {}

func (x *ListCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_collection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_collection_proto_rawDescGZIP(), []int{3}
}

func (x *ListCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListCollectionResponse represents a response to retrieve a collection
type ListCollectionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// retrieved collection
	Collection    *Collection `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionResponse) Reset() {
	*x = ListCollectionResponse{}
	mi := &file_api_proto_v1_collection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionResponse) ProtoMessage() {}

func (x *ListCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_collection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_collection_proto_rawDescGZIP(), []int{4}
}

func (x *ListCollectionResponse) GetCollection() *Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

// ListCollectionsRequest represents a request to list collections
type ListCollectionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// limit and offset for pagination
	Limit         int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_api_proto_v1_collection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_collection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_collection_proto_rawDescGZIP(), []int{5}
}

func (x *ListCollectionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCollectionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// ListCollectionsResponse represents a response to list collections
type ListCollectionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// list of collections
	Collections   []*Collection `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_api_proto_v1_collection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_collection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_collection_proto_rawDescGZIP(), []int{6}
}

func (x *ListCollectionsResponse) GetCollections() []*Collection {
	if x != nil {
		return x.Collections
	}
	return nil
}

// DeleteCollectionRequest represents a request to delete a collection
type DeleteCollectionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the collection to delete
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionRequest) Reset() {
	*x = DeleteCollectionRequest{}
	mi := &file_api_proto_v1_collection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionRequest) ProtoMessage() {}

func (x *DeleteCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_collection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteCollectionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_collection_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteCollectionResponse represents a response to delete a collection
type DeleteCollectionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the deleted collection
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// timestamp of the deletion
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	// no of documents deleted
	DocumentDeleted int64 `protobuf:"varint,3,opt,name=document_deleted,json=documentDeleted,proto3" json:"document_deleted,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteCollectionResponse) Reset() {
	*x = DeleteCollectionResponse{}
	mi := &file_api_proto_v1_collection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionResponse) ProtoMessage() {}

func (x *DeleteCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_collection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionResponse.ProtoReflect.Descriptor instead.
func (*DeleteCollectionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_collection_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCollectionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteCollectionResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *DeleteCollectionResponse) GetDocumentDeleted() int64 {
	if x != nil {
		return x.DocumentDeleted
	}
	return 0
}

var File_api_proto_v1_collection_proto protoreflect.FileDescriptor

const file_api_proto_v1_collection_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/v1/collection.proto\x12\vcollections\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x03\n" +
	"\n" +
	"Collection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12)\n" +
	"\x10vector_dimension\x18\x05 \x01(\x05R\x0fvectorDimension\x12T\n" +
	"\x0fmetadata_schema\x18\x06 \x03(\v2+.collections.Collection.MetadataSchemaEntryR\x0emetadataSchema\x12%\n" +
	"\x0edocument_count\x18\a \x01(\x03R\rdocumentCount\x1aZ\n" +
	"\x13MetadataSchemaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value:\x028\x01\"\x97\x02\n" +
	"\x17CreateCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x10vector_dimension\x18\x02 \x01(\x05R\x0fvectorDimension\x12a\n" +
	"\x0fmetadata_schema\x18\x03 \x03(\v28.collections.CreateCollectionRequest.MetadataSchemaEntryR\x0emetadataSchema\x1aZ\n" +
	"\x13MetadataSchemaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value:\x028\x01\"S\n" +
	"\x18CreateCollectionResponse\x127\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2\x17.collections.CollectionR\n" +
	"collection\"'\n" +
	"\x15ListCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Q\n" +
	"\x16ListCollectionResponse\x127\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2\x17.collections.CollectionR\n" +
	"collection\"F\n" +
	"\x16ListCollectionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"T\n" +
	"\x17ListCollectionsResponse\x129\n" +
	"\vcollections\x18\x01 \x03(\v2\x17.collections.CollectionR\vcollections\")\n" +
	"\x17DeleteCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x90\x01\n" +
	"\x18DeleteCollectionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"deleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12)\n" +
	"\x10document_deleted\x18\x03 \x01(\x03R\x0fdocumentDeleted2\x8e\x03\n" +
	"\x11CollectionService\x12_\n" +
	"\x10CreateCollection\x12$.collections.CreateCollectionRequest\x1a%.collections.CreateCollectionResponse\x12Y\n" +
	"\x0eListCollection\x12\".collections.ListCollectionRequest\x1a#.collections.ListCollectionResponse\x12\\\n" +
	"\x0fListCollections\x12#.collections.ListCollectionsRequest\x1a$.collections.ListCollectionsResponse\x12_\n" +
	"\x10DeleteCollection\x12$.collections.DeleteCollectionRequest\x1a%.collections.DeleteCollectionResponseB0Z.github.com/Annany2002/vector-sync/api/proto/v1b\x06proto3"

var (
	file_api_proto_v1_collection_proto_rawDescOnce sync.Once
	file_api_proto_v1_collection_proto_rawDescData []byte
)

func file_api_proto_v1_collection_proto_rawDescGZIP() []byte {
	file_api_proto_v1_collection_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_collection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_collection_proto_rawDesc), len(file_api_proto_v1_collection_proto_rawDesc)))
	})
	return file_api_proto_v1_collection_proto_rawDescData
}

var file_api_proto_v1_collection_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_v1_collection_proto_goTypes = []any{
	(*Collection)(nil),               // 0: collections.Collection
	(*CreateCollectionRequest)(nil),  // 1: collections.CreateCollectionRequest
	(*CreateCollectionResponse)(nil), // 2: collections.CreateCollectionResponse
	(*ListCollectionRequest)(nil),    // 3: collections.ListCollectionRequest
	(*ListCollectionResponse)(nil),   // 4: collections.ListCollectionResponse
	(*ListCollectionsRequest)(nil),   // 5: collections.ListCollectionsRequest
	(*ListCollectionsResponse)(nil),  // 6: collections.ListCollectionsResponse
	(*DeleteCollectionRequest)(nil),  // 7: collections.DeleteCollectionRequest
	(*DeleteCollectionResponse)(nil), // 8: collections.DeleteCollectionResponse
	nil,                              // 9: collections.Collection.MetadataSchemaEntry
	nil,                              // 10: collections.CreateCollectionRequest.MetadataSchemaEntry
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
	(*structpb.Struct)(nil),          // 12: google.protobuf.Struct
}
var file_api_proto_v1_collection_proto_depIdxs = []int32{
	11, // 0: collections.Collection.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: collections.Collection.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 2: collections.Collection.metadata_schema:type_name -> collections.Collection.MetadataSchemaEntry
	10, // 3: collections.CreateCollectionRequest.metadata_schema:type_name -> collections.CreateCollectionRequest.MetadataSchemaEntry
	0,  // 4: collections.CreateCollectionResponse.collection:type_name -> collections.Collection
	0,  // 5: collections.ListCollectionResponse.collection:type_name -> collections.Collection
	0,  // 6: collections.ListCollectionsResponse.collections:type_name -> collections.Collection
	11, // 7: collections.DeleteCollectionResponse.deleted_at:type_name -> google.protobuf.Timestamp
	12, // 8: collections.Collection.MetadataSchemaEntry.value:type_name -> google.protobuf.Struct
	12, // 9: collections.CreateCollectionRequest.MetadataSchemaEntry.value:type_name -> google.protobuf.Struct
	1,  // 10: collections.CollectionService.CreateCollection:input_type -> collections.CreateCollectionRequest
	3,  // 11: collections.CollectionService.ListCollection:input_type -> collections.ListCollectionRequest
	5,  // 12: collections.CollectionService.ListCollections:input_type -> collections.ListCollectionsRequest
	7,  // 13: collections.CollectionService.DeleteCollection:input_type -> collections.DeleteCollectionRequest
	2,  // 14: collections.CollectionService.CreateCollection:output_type -> collections.CreateCollectionResponse
	4,  // 15: collections.CollectionService.ListCollection:output_type -> collections.ListCollectionResponse
	6,  // 16: collections.CollectionService.ListCollections:output_type -> collections.ListCollectionsResponse
	8,  // 17: collections.CollectionService.DeleteCollection:output_type -> collections.DeleteCollectionResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_proto_v1_collection_proto_init() }
func file_api_proto_v1_collection_proto_init() {
	if File_api_proto_v1_collection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_collection_proto_rawDesc), len(file_api_proto_v1_collection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_collection_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_collection_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_collection_proto_msgTypes,
	}.Build()
	File_api_proto_v1_collection_proto = out.File
	file_api_proto_v1_collection_proto_goTypes = nil
	file_api_proto_v1_collection_proto_depIdxs = nil
}
