syntax = "proto3";

package collections;

option go_package = "github.com/Annany2002/vector-sync/api/proto/v1";

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

// Collections represents a collection of documents
message Collection {
    // unique id of the collection
    string id = 1;
    // creation timestamp
    google.protobuf.Timestamp created_at = 2;
    // update timestamp
    google.protobuf.Timestamp updated_at = 3;
    // name of the collection (must be unique)
    string name = 4;
    // dimension of the vector space
    int32 vector_dimension = 5;
    // schema for metadata
    map<string, google.protobuf.Struct> metadata_schema = 6;
    // number of documents in this collection
    int64 document_count = 7;
}


// CreateCollectionRequest represents a request to create a collection
message CreateCollectionRequest {
    // name of the collection (must be unique)
    string name = 1;
    // dimension of the vector space
    int32 vector_dimension = 2;
    // schema for metadata
    map<string, google.protobuf.Struct> metadata_schema = 3;
}

// CreateCollectionResponse represents a response to create a collection
message CreateCollectionResponse {
    // created collection
    Collection collection = 1;
}

// ListCollectionRequest represents a request to retrieve a collection
message ListCollectionRequest {
    // id of the collection to retrieve
    string id = 1;
}

// ListCollectionResponse represents a response to retrieve a collection
message ListCollectionResponse {
    // retrieved collection
    Collection collection = 1;
}

// ListCollectionsRequest represents a request to list collections
message ListCollectionsRequest {
    // limit and offset for pagination
    int32 limit = 1;
    int32 offset = 2;
}

// ListCollectionsResponse represents a response to list collections
message ListCollectionsResponse {
    // list of collections
    repeated Collection collections = 1;
}

// DeleteCollectionRequest represents a request to delete a collection
message DeleteCollectionRequest {
    // id of the collection to delete
    string id = 1;
}

// DeleteCollectionResponse represents a response to delete a collection
message DeleteCollectionResponse {
    // id of the deleted collection
    string id = 1;
    // timestamp of the deletion
    google.protobuf.Timestamp deleted_at = 2;
    // no of documents deleted
    int64 document_deleted = 3;
}

// CollectionService provides collection management operations
service CollectionService {
    rpc CreateCollection (CreateCollectionRequest) returns (CreateCollectionResponse);
    rpc ListCollection (ListCollectionRequest) returns (ListCollectionResponse);
    rpc ListCollections (ListCollectionsRequest) returns (ListCollectionsResponse);
    rpc DeleteCollection (DeleteCollectionRequest) returns (DeleteCollectionResponse);
}