// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/v1/document.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Document represents a document in a collection
type Document struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// unique id of the document
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// update timestamp
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// id of the collection the document belongs to
	CollectionId string `protobuf:"bytes,4,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	// content of the document
	Content string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	// vector representation of the document
	Vector []float32 `protobuf:"fixed32,6,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	// metadata associated with the document
	Metadata      map[string]*structpb.Struct `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_api_proto_v1_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_document_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Document) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Document) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *Document) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Document) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *Document) GetMetadata() map[string]*structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CreateDocumentRequest represents a request to create a document
type CreateDocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the collection the document belongs to
	CollectionId string `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	// content of the document
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// vector representation of the document
	Vector []float32 `protobuf:"fixed32,3,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	// metadata associated with the document
	Metadata      map[string]*structpb.Struct `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocumentRequest) Reset() {
	*x = CreateDocumentRequest{}
	mi := &file_api_proto_v1_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentRequest) ProtoMessage() {}

func (x *CreateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentRequest.ProtoReflect.Descriptor instead.
func (*CreateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_document_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDocumentRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *CreateDocumentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateDocumentRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *CreateDocumentRequest) GetMetadata() map[string]*structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CreateDocumentResponse represents a response to create a document
type CreateDocumentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// created document
	Document      *Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocumentResponse) Reset() {
	*x = CreateDocumentResponse{}
	mi := &file_api_proto_v1_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentResponse) ProtoMessage() {}

func (x *CreateDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentResponse.ProtoReflect.Descriptor instead.
func (*CreateDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_document_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDocumentResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

// ListDocumentRequest represents a request to list a single document
type ListDocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the document to list
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentRequest) Reset() {
	*x = ListDocumentRequest{}
	mi := &file_api_proto_v1_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentRequest) ProtoMessage() {}

func (x *ListDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_document_proto_rawDescGZIP(), []int{3}
}

func (x *ListDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListDocumentResponse represents a response to list a single document
type ListDocumentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// retrieved document
	Document      *Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentResponse) Reset() {
	*x = ListDocumentResponse{}
	mi := &file_api_proto_v1_document_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentResponse) ProtoMessage() {}

func (x *ListDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_document_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_document_proto_rawDescGZIP(), []int{4}
}

func (x *ListDocumentResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

// ListDocumentsRequest represents a request to list documents
type ListDocumentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the collection to list documents from
	CollectionId string `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	// number of documents to return
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// offset for pagination
	Offset        int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_api_proto_v1_document_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_document_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_document_proto_rawDescGZIP(), []int{5}
}

func (x *ListDocumentsRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *ListDocumentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDocumentsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// ListDocumentsResponse represents a response to list documents
type ListDocumentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// list of documents
	Documents     []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_api_proto_v1_document_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_document_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_document_proto_rawDescGZIP(), []int{6}
}

func (x *ListDocumentsResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

// DeleteDocumentRequest represents a request to delete a document
type DeleteDocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the document to delete
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_api_proto_v1_document_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_document_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_document_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteDocumentResponse represents a response to delete a document
type DeleteDocumentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the deleted document
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// timestamp of the deletion
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentResponse) Reset() {
	*x = DeleteDocumentResponse{}
	mi := &file_api_proto_v1_document_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentResponse) ProtoMessage() {}

func (x *DeleteDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_document_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_document_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDocumentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteDocumentResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_api_proto_v1_document_proto protoreflect.FileDescriptor

const file_api_proto_v1_document_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/v1/document.proto\x12\bdocument\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfb\x02\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12#\n" +
	"\rcollection_id\x18\x04 \x01(\tR\fcollectionId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x16\n" +
	"\x06vector\x18\x06 \x03(\x02R\x06vector\x12<\n" +
	"\bmetadata\x18\a \x03(\v2 .document.Document.MetadataEntryR\bmetadata\x1aT\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value:\x028\x01\"\x8f\x02\n" +
	"\x15CreateDocumentRequest\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\tR\fcollectionId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06vector\x18\x03 \x03(\x02R\x06vector\x12I\n" +
	"\bmetadata\x18\x04 \x03(\v2-.document.CreateDocumentRequest.MetadataEntryR\bmetadata\x1aT\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value:\x028\x01\"H\n" +
	"\x16CreateDocumentResponse\x12.\n" +
	"\bdocument\x18\x01 \x01(\v2\x12.document.DocumentR\bdocument\"%\n" +
	"\x13ListDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x14ListDocumentResponse\x12.\n" +
	"\bdocument\x18\x01 \x01(\v2\x12.document.DocumentR\bdocument\"i\n" +
	"\x14ListDocumentsRequest\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\tR\fcollectionId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"I\n" +
	"\x15ListDocumentsResponse\x120\n" +
	"\tdocuments\x18\x01 \x03(\v2\x12.document.DocumentR\tdocuments\"'\n" +
	"\x15DeleteDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"c\n" +
	"\x16DeleteDocumentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"deleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt2\xdc\x02\n" +
	"\x0fDocumentService\x12S\n" +
	"\x0eCreateDocument\x12\x1f.document.CreateDocumentRequest\x1a .document.CreateDocumentResponse\x12M\n" +
	"\fListDocument\x12\x1d.document.ListDocumentRequest\x1a\x1e.document.ListDocumentResponse\x12P\n" +
	"\rListDocuments\x12\x1e.document.ListDocumentsRequest\x1a\x1f.document.ListDocumentsResponse\x12S\n" +
	"\x0eDeleteDocument\x12\x1f.document.DeleteDocumentRequest\x1a .document.DeleteDocumentResponseB0Z.github.com/Annany2002/vector-sync/api/proto/v1b\x06proto3"

var (
	file_api_proto_v1_document_proto_rawDescOnce sync.Once
	file_api_proto_v1_document_proto_rawDescData []byte
)

func file_api_proto_v1_document_proto_rawDescGZIP() []byte {
	file_api_proto_v1_document_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_document_proto_rawDesc), len(file_api_proto_v1_document_proto_rawDesc)))
	})
	return file_api_proto_v1_document_proto_rawDescData
}

var file_api_proto_v1_document_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_v1_document_proto_goTypes = []any{
	(*Document)(nil),               // 0: document.Document
	(*CreateDocumentRequest)(nil),  // 1: document.CreateDocumentRequest
	(*CreateDocumentResponse)(nil), // 2: document.CreateDocumentResponse
	(*ListDocumentRequest)(nil),    // 3: document.ListDocumentRequest
	(*ListDocumentResponse)(nil),   // 4: document.ListDocumentResponse
	(*ListDocumentsRequest)(nil),   // 5: document.ListDocumentsRequest
	(*ListDocumentsResponse)(nil),  // 6: document.ListDocumentsResponse
	(*DeleteDocumentRequest)(nil),  // 7: document.DeleteDocumentRequest
	(*DeleteDocumentResponse)(nil), // 8: document.DeleteDocumentResponse
	nil,                            // 9: document.Document.MetadataEntry
	nil,                            // 10: document.CreateDocumentRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),  // 11: google.protobuf.Timestamp
	(*structpb.Struct)(nil),        // 12: google.protobuf.Struct
}
var file_api_proto_v1_document_proto_depIdxs = []int32{
	11, // 0: document.Document.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: document.Document.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 2: document.Document.metadata:type_name -> document.Document.MetadataEntry
	10, // 3: document.CreateDocumentRequest.metadata:type_name -> document.CreateDocumentRequest.MetadataEntry
	0,  // 4: document.CreateDocumentResponse.document:type_name -> document.Document
	0,  // 5: document.ListDocumentResponse.document:type_name -> document.Document
	0,  // 6: document.ListDocumentsResponse.documents:type_name -> document.Document
	11, // 7: document.DeleteDocumentResponse.deleted_at:type_name -> google.protobuf.Timestamp
	12, // 8: document.Document.MetadataEntry.value:type_name -> google.protobuf.Struct
	12, // 9: document.CreateDocumentRequest.MetadataEntry.value:type_name -> google.protobuf.Struct
	1,  // 10: document.DocumentService.CreateDocument:input_type -> document.CreateDocumentRequest
	3,  // 11: document.DocumentService.ListDocument:input_type -> document.ListDocumentRequest
	5,  // 12: document.DocumentService.ListDocuments:input_type -> document.ListDocumentsRequest
	7,  // 13: document.DocumentService.DeleteDocument:input_type -> document.DeleteDocumentRequest
	2,  // 14: document.DocumentService.CreateDocument:output_type -> document.CreateDocumentResponse
	4,  // 15: document.DocumentService.ListDocument:output_type -> document.ListDocumentResponse
	6,  // 16: document.DocumentService.ListDocuments:output_type -> document.ListDocumentsResponse
	8,  // 17: document.DocumentService.DeleteDocument:output_type -> document.DeleteDocumentResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_proto_v1_document_proto_init() }
func file_api_proto_v1_document_proto_init() {
	if File_api_proto_v1_document_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_document_proto_rawDesc), len(file_api_proto_v1_document_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_document_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_document_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_document_proto_msgTypes,
	}.Build()
	File_api_proto_v1_document_proto = out.File
	file_api_proto_v1_document_proto_goTypes = nil
	file_api_proto_v1_document_proto_depIdxs = nil
}
