syntax = "proto3";

package document;

option go_package = "github.com/Annany2002/vector-sync/api/proto/v1";

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

// Document represents a document in a collection
message Document {
    // unique id of the document
    string id = 1;
    // creation timestamp
    google.protobuf.Timestamp created_at = 2;
    // update timestamp
    google.protobuf.Timestamp updated_at = 3;
    // id of the collection the document belongs to
    string collection_id = 4;
    // content of the document
    string content = 5;
    // vector representation of the document
    repeated float vector = 6;
    // metadata associated with the document
    map<string, google.protobuf.Struct> metadata = 7;
}

// CreateDocumentRequest represents a request to create a document
message CreateDocumentRequest {
    // id of the collection the document belongs to
    string collection_id = 1;
    // content of the document
    string content = 2;
    // vector representation of the document
    repeated float vector = 3;
    // metadata associated with the document
    map<string, google.protobuf.Struct> metadata = 4;
}

// CreateDocumentResponse represents a response to create a document
message CreateDocumentResponse {
    // created document
    Document document = 1;
}

// ListDocumentRequest represents a request to list a single document
message ListDocumentRequest {
    // id of the document to list
    string id = 1;
}

// ListDocumentResponse represents a response to list a single document
message ListDocumentResponse {
    // retrieved document
    Document document = 1;
}

// ListDocumentsRequest represents a request to list documents
message ListDocumentsRequest {
    // id of the collection to list documents from
    string collection_id = 1;
    // number of documents to return
    int32 limit = 2;
    // offset for pagination
    int32 offset = 3;
}

// ListDocumentsResponse represents a response to list documents
message ListDocumentsResponse {
    // list of documents
    repeated Document documents = 1;
}

// DeleteDocumentRequest represents a request to delete a document
message DeleteDocumentRequest {
    // id of the document to delete
    string id = 1;
}

// DeleteDocumentResponse represents a response to delete a document
message DeleteDocumentResponse {
    // id of the deleted document
    string id = 1;
    // timestamp of the deletion
    google.protobuf.Timestamp deleted_at = 2;
}

// DocumentService provides document management operations
service DocumentService {
    rpc CreateDocument (CreateDocumentRequest) returns (CreateDocumentResponse);
    rpc ListDocument (ListDocumentRequest) returns (ListDocumentResponse);
    rpc ListDocuments (ListDocumentsRequest) returns (ListDocumentsResponse);
    rpc DeleteDocument (DeleteDocumentRequest) returns (DeleteDocumentResponse);
}